version: '3'

services:
  duckdns:
    container_name: Duckdns
    image: mikygus/duckdns-updater:1.0
    restart: unless-stopped
    hostname: duckdns
    environment:
      DUCKDNS_ENV_DOMAINS: "barmy"
      DUCKDNS_ENV_TOKEN: "${DUCKDNS_TOKEN}"
